/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-08-24 03:31:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dictionary_002ddetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\" />\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
      out.write("<title>YOGA POSE</title>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/dictionary-detail.css\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<header></header>\n");
      out.write("\t<main>\n");
      out.write("\t\t<div class=\"yoag-dictionary-box\">\n");
      out.write("\t\t\t<div class=\"yoag-dictionary-box-section\">\n");
      out.write("\t\t\t\t<div class=\"yoag-dictionary\">\n");
      out.write("\t\t\t\t\t<p>&#60; Yoga Dictionary</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"yoga-title-box\">\n");
      out.write("\t\t\t<div class=\"yoga-title-box-section\">\n");
      out.write("\t\t\t\t<div class=\"yoga-title\">\n");
      out.write("\t\t\t\t\t<h2>This is Pose1 : 산자세</h2>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"search-img_yoga-title\">\n");
      out.write("\t\t\t<div class=\"search-img\">\n");
      out.write("\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/dictionary-detail/bg01.jpg\" alt=\"불러오지 못함\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"search-img2\">\n");
      out.write("\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/dictionary-detail/bg02.jpg\" alt=\"불러오지 못함\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"yoga-second-dificult-box\">\n");
      out.write("\t\t\t<div class=\"yoga-second-dificult-box-section\">\n");
      out.write("\t\t\t\t<div class=\"yoga-second-dificult\">\n");
      out.write("\t\t\t\t\t<span>CLCOCK 60SEC</span> <span>DIFFI 5</span>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"box\">\n");
      out.write("\t\t\t<div class=\"box_section\">\n");
      out.write("\t\t\t\t<div class=\"box-stepBystep\">\n");
      out.write("\t\t\t\t\t<div class=\"stepBystep-title\">\n");
      out.write("\t\t\t\t\t\t<p>Step by step</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"stepBystep-content\">\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li>From a sitting position, bend your knees to the right\n");
      out.write("\t\t\t\t\t\t\t\tand shift your feet to the left - so that your left ankle ends\n");
      out.write("\t\t\t\t\t\t\t\tup resting in the arch of your right foot</li>\n");
      out.write("\t\t\t\t\t\t\t<li>Press your sitting bones to the mat to lengthen the\n");
      out.write("\t\t\t\t\t\t\t\tspine as you inhale. Then with the support of your arms twist\n");
      out.write("\t\t\t\t\t\t\t\ttowards the right on an exhalation - your left hip may raise a\n");
      out.write("\t\t\t\t\t\t\t\tlittle.</li>\n");
      out.write("\t\t\t\t\t\t\t<li>Turn your head and neck last, firmly pressing the\n");
      out.write("\t\t\t\t\t\t\t\tfingertips of your right hand into the floor</li>\n");
      out.write("\t\t\t\t\t\t\t<li>Keep lengthening your spine as you inhale and explore\n");
      out.write("\t\t\t\t\t\t\t\tthe depth of your twist as you exhale, stay for a few breaths</li>\n");
      out.write("\t\t\t\t\t\t\t<li>To come out of this pose, release your hands, bring your\n");
      out.write("\t\t\t\t\t\t\t\ttorso to the front and straighten your legs</li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"box-BeginnersTips\">\n");
      out.write("\t\t\t\t\t<div class=\"BeginnersTips-title\">\n");
      out.write("\t\t\t\t\t\t<p>Beginners tips</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"BeginnersTips-content\">\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li>If your sitting bones are not firmly grounded, i.e. you\n");
      out.write("\t\t\t\t\t\t\t\tare tilting onto the twisting side, try sitting up on a thickly\n");
      out.write("\t\t\t\t\t\t\t\tfolded blanket.</li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"box-Benefits\">\n");
      out.write("\t\t\t\t\t<div class=\"Benefits-title\">\n");
      out.write("\t\t\t\t\t\t<p>Benefits</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"Benefits-content\">\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li>Keeps your spine mobile</li>\n");
      out.write("\t\t\t\t\t\t\t<li>Massages the abdominal organs and improves digestion</li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"box-watchOutFor\">\n");
      out.write("\t\t\t\t\t<div class=\"watchOutFor-title\">\n");
      out.write("\t\t\t\t\t\t<p>Watch out for</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"watchOutFor-content\">\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li>Ground your sitting bones to lengthen the spine, then\n");
      out.write("\t\t\t\t\t\t\t\tallow your hips to follow your spine in the twist to some degree</li>\n");
      out.write("\t\t\t\t\t\t\t<li>Length in the spine is more important than the depth of\n");
      out.write("\t\t\t\t\t\t\t\tthe twist.</li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"box-variations\">\n");
      out.write("\t\t\t\t\t<div class=\"variations-title\">\n");
      out.write("\t\t\t\t\t\t<p>Variations</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"variations-content\">\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li>For an easier version, sit sideways on a chair, with the\n");
      out.write("\t\t\t\t\t\t\t\tback of the chair to your right. Bring your knees together and\n");
      out.write("\t\t\t\t\t\t\t\theels directly below the knees. Exhale and twist toward the back\n");
      out.write("\t\t\t\t\t\t\t\tof the chair. Hold onto the sides of the chair and make the\n");
      out.write("\t\t\t\t\t\t\t\tmovement of trying to pull the chair apart.</li>\n");
      out.write("\t\t\t\t\t\t\t<li>You can increase the challenge further by changing the\n");
      out.write("\t\t\t\t\t\t\t\tposition of your arms and hands. Exhale and swing your right arm\n");
      out.write("\t\t\t\t\t\t\t\taround behind your back as you twist to the right. Hold the left\n");
      out.write("\t\t\t\t\t\t\t\tarm just at the elbow (if you can reach, otherwise take hold of\n");
      out.write("\t\t\t\t\t\t\t\tyour shirt). Turn your left arm outward and slip the hand under\n");
      out.write("\t\t\t\t\t\t\t\tthe right knee, palm on the floor.</li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</main>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
