/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-08-28 08:40:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.springframework.web.context.ContextLoader;
import org.springframework.web.context.WebApplicationContext;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/Users/minjae/Documents/GitHub/YOGAYO/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/YOGAYO/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1598411615000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.springframework.web.context.ContextLoader");
    _jspx_imports_classes.add("org.springframework.web.context.WebApplicationContext");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("   \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"UTF-8\" />\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
      out.write("    <title>YOGAYO | MY PAGE</title>\n");
      out.write("     <link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/mypage.css\">\n");
      out.write("    <script\n");
      out.write("      type=\"text/javascript\"\n");
      out.write("      src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js\"\n");
      out.write("    ></script>\n");
      out.write("    <script\n");
      out.write("      type=\"text/javascript\"\n");
      out.write("      src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js\"\n");
      out.write("    ></script>\n");
      out.write("    <script src=\"https://code.jquery.com/jquery.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/myPage.js\"></script>\n");
      out.write("    <script>\n");
      out.write("    var data1 = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count1week}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\n");
      out.write("    var data2 = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count2week}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\n");
      out.write("    var data3 = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count3week}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\n");
      out.write("    var data4 = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count4week}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\n");
      out.write("\n");
      out.write(" \n");
      out.write("    </script>\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("    <header></header>\n");
      out.write("    <main>\n");
      out.write("      <div class=\"content\">\n");
      out.write("        <div class=\"content_top\">\n");
      out.write("          <div class=\"content_top_welcome\">\n");
      out.write("            <div class=\"content_top_faceImg\"></div>\n");
      out.write("            <div class=\"content_top_welcomeTxt\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 님의 기록</div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"content_top_btn\">\n");
      out.write("            <button class=\"content_top_btn_edit\" onclick=\"location.href='update'\">정보 수정</button>\n");
      out.write("            <button class=\"content_top_btn_addCrs\">코스 추가</button>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"content_front\">\n");
      out.write("          <div class=\"front_first\">\n");
      out.write("            <div class=\"front_first_title\">현재 몸무게</div>\n");
      out.write("            <div class=\"front_first_value\">\n");
      out.write("              <div class=\"first_value1\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cWeight}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" kg</div>\n");
      out.write("              <div class=\"first_value2\"></div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"front_second\">\n");
      out.write("            <div class=\"front_second_title\">이번달 감량 몸무게</div>\n");
      out.write("            <div class=\"front_second_value\">\n");
      out.write("              <div class=\"second_value1\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tWeight}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" kg</div>\n");
      out.write("              <div class=\"second_value2\"></div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"front_third\">\n");
      out.write("            <div class=\"front_third_title\">지난 달 감량 몸무게</div>\n");
      out.write("            <div class=\"front_third_value\">\n");
      out.write("              <div class=\"third_value1\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lWeight}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" kg</div>\n");
      out.write("              <div class=\"third_value2\"></div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"content_middle\">\n");
      out.write("          <div class=\"statistics\">\n");
      out.write("            <div class=\"statistics_1\">\n");
      out.write("              <div class=\"statistics_title\">내 기록 모아보기</div>\n");
      out.write("              <div class=\"graph\">\n");
      out.write("                <ul class=\"months\">\n");
      out.write("                  <li>Jan</li>\n");
      out.write("                  <li>Feb</li>\n");
      out.write("                  <li>Mar</li>\n");
      out.write("                  <li>Apr</li>\n");
      out.write("                </ul>\n");
      out.write("                <ul class=\"days\">\n");
      out.write("                  <li>Sun</li>\n");
      out.write("                  <li>Mon</li>\n");
      out.write("                  <li>Tue</li>\n");
      out.write("                  <li>Wed</li>\n");
      out.write("                  <li>Thu</li>\n");
      out.write("                  <li>Fri</li>\n");
      out.write("                  <li>Sat</li>\n");
      out.write("                </ul>\n");
      out.write("                <ul class=\"squares\">\n");
      out.write("                  <!-- added via javascript -->\n");
      out.write("                </ul>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"statistics_2\">\n");
      out.write("              <div class=\"stat2_title\">피드 올린 횟수</div>\n");
      out.write("              <canvas id=\"stat2\"></canvas>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"statistics_3\">\n");
      out.write("              <div class=\"stat3_title\">피드 올린 횟수</div>\n");
      out.write("              <canvas id=\"stat3\"></canvas>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"statistics_4\">\n");
      out.write("              <div class=\"stat4_title\">피드 올린 횟수</div>\n");
      out.write("              <canvas id=\"stat4\"></canvas>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        \n");
      out.write("        <div class=\"content_bottom\">\n");
      out.write("          <div class=\"content_bottom_rcdlist need_scrollbar\">\n");
      out.write("            <div class=\"content_bottom_myRcds\">\n");
      out.write("              <div class=\"content_bottom_myRcds_title\">내 요가 후기</div>\n");
      out.write("              <div class=\"content_bottom_myRcds_wrap\">\n");
      out.write("                <div class=\"content_bottom_myRcds_info\">\n");
      out.write("                  <div class=\"content_bottom_myRcds_top\">\n");
      out.write("                    <div class=\"myRcds_time\">\n");
      out.write("                      <span class=\"myRcds_time_txt\">오늘 요가 시간:</span>\n");
      out.write("                      <div class=\"myRcds_time_usrtime\"></div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"myRcds_crs\">\n");
      out.write("                      <span class=\"myRcds_crs_txt\">진행 코스:</span>\n");
      out.write("                      <div class=\"myRcds_crs_crsname\"></div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"myRcds_stf\">\n");
      out.write("                      <span class=\"myRcds_stf_txt\">나의 만족도:</span>\n");
      out.write("                      <div class=\"myRcds_stf_usrstf\"></div>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"content_bottom_myRcds_middle\">\n");
      out.write("                    <div class=\"middle_txt\"><br /></div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"content_bottom_myRcds_bottom\">\n");
      out.write("                    <div class=\"bottom_time\"></div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <img src=\"\" class=\"content_bottom_myRcds_img\">\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"content_bottom_myCrs need_scrollbar\">\n");
      out.write("            <div class=\"myCrs_title\">나만의 코스 리스트</div>\n");
      out.write("            \n");
      out.write("            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            \n");
      out.write("          </div>\n");
      out.write("          <div class=\"content_bottom_likes need_scrollbar\">\n");
      out.write("            <div class=\"likes_title\">좋아요한 코스 리스트</div>\n");
      out.write("            <div class=\"likes_content\">\n");
      out.write("              <div class=\"likes_content_img\"></div>\n");
      out.write("              <span class=\"likes_content_txt\">요가 코스1</span>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"likes_content\">\n");
      out.write("              <div class=\"likes_content_img\"></div>\n");
      out.write("              <span class=\"likes_content_txt\">요가 코스1</span>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"likes_content\">\n");
      out.write("              <div class=\"likes_content_img\"></div>\n");
      out.write("              <span class=\"likes_content_txt\">요가 코스1</span>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"likes_content\">\n");
      out.write("              <div class=\"likes_content_img\"></div>\n");
      out.write("              <span class=\"likes_content_txt\">요가 코스1</span>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"likes_content\">\n");
      out.write("              <div class=\"likes_content_img\"></div>\n");
      out.write("              <span class=\"likes_content_txt\">요가 코스1</span>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"likes_content\">\n");
      out.write("              <div class=\"likes_content_img\"></div>\n");
      out.write("              <span class=\"likes_content_txt\">요가 코스1</span>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"likes_content\">\n");
      out.write("              <div class=\"likes_content_img\"></div>\n");
      out.write("              <span class=\"likes_content_txt\">요가 코스1</span>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </main>\n");
      out.write("    <footer></footer>\n");
      out.write("    \t<script language=JavaScript\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/graph.js\"></script>\n");
      out.write("\t\t<script language=JavaScript\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/square.js\"></script>\n");
      out.write("  </body>\n");
      out.write("</html>\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/mypage.jsp(147,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("i");
      // /WEB-INF/views/mypage.jsp(147,12) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${crsList }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("            <div class=\"myCrs_box\">\n");
            out.write("              <div class=\"myCrs_top\">\n");
            out.write("                <div class=\"myCrs_top_img\">\n");
            out.write("                \t<img class=\"forImg\" alt=\"오류!\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.imgPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\n");
            out.write("                </div>\n");
            out.write("                <div class=\"myCrs_top_title\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\n");
            out.write("              </div>\n");
            out.write("              <div class=\"myCrs_bottom\">\n");
            out.write("                <div class=\"myCrs_bottom_content\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.dscrt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\n");
            out.write("              </div>\n");
            out.write("            </div>\n");
            out.write("           ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
