/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-09-04 01:39:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sign_002dup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/kosmo_28/Documents/GitHub/YOGAYO/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/YOGAYO/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1598413005219L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<title>YOGAYO | 회원가입</title>\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/ae58912594.js\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/sign-up.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<script>\r\n");
Object[] keyword = (Object[]) request.getAttribute("keyword");
			Integer length = (Integer) request.getAttribute("length");
      out.write("\r\n");
      out.write("\tvar numArr=new Array();\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t\t");
for (int i = 0; i < length; i++) {
      out.write("\r\n");
      out.write("\t\tnumArr.push(\"");
      out.print(keyword[i]);
      out.write("\")\r\n");
}
      out.write("\r\n");
      out.write("\tlet randomNums = [];\r\n");
      out.write("\t\t\t\twhile (numArr.length > 0) { // 추출을 원하는 갯수\r\n");
      out.write("\t\t\t\t\tlet target = numArr.splice(Math.floor(Math.random()* numArr.length), 1)[0];\r\n");
      out.write("\t\t\t\t\trandomNums.push(target);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\tfor(var i=0; i<23;i++){\t\t\t\r\n");
      out.write("\t$(\".interests\").append('<span class=\"interest\">'+randomNums[i]+'</span>')\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("</script>\r\n");
      out.write("\t<script language=JavaScript src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/sign_up_interests.js\"></script>\r\n");
      out.write("\t<main>\r\n");
      out.write("\t\t<section id=\"step_1\">\r\n");
      out.write("\t\t\t<header>\r\n");
      out.write("\t\t\t\t<a href=\"/\"><div class=\"logo-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t<span>YOGAYO</span>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"box-div\"></div>\r\n");
      out.write("\t\t\t\t\t</div> </a>\r\n");
      out.write("\t\t\t</header>\r\n");
      out.write("\t\t\t<span class=\"welcome\">좋아요! 이제 간단한 두 단계만 거치면 YOGAYO와 함께 하실 수\r\n");
      out.write("\t\t\t\t있습니다.</span> <span class=\"step_1\">1. 회원가입을 위한 정보를 입력해주세요.</span>\r\n");
      out.write("\t\t\t<div class=\"sign-up-form\">\r\n");
      out.write("\t\t\t\t<form action=\"sign-up\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"keyword\" id=\"keyword\" value=\"false\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<label for=\"\">이메일</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"id\" id=\"email\" placeholder=\"johndoe@example.com\" /> <br /> \r\n");
      out.write("\t\t\t\t\t\t<div class=\"msgContainer\"><label for=\"\"></label><span class=\"emailVaildMsg\" >이미 사용중이거나 올바르지 않은 이메일입니다.</span><br /></div>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"\">이름</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"name\" id=\"name\" placeholder=\"3자 이상\" /><br /> \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<label for=\"\">생년월일</label> <input type=\"date\" name=\"bDate\" id=\"birthDay\" placeholder=\"\" /><br /> <label for=\"\">성별</label>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"gender\" id=\"gender\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"M\">남성</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"F\">여성</option>\r\n");
      out.write("\t\t\t\t\t</select> <br /> \r\n");
      out.write("\t\t\t\t\t<label for=\"\">숙련도</label> \r\n");
      out.write("\t\t\t\t <select name=\"profiLevel\" id=\"profiLevel\">\r\n");
      out.write("\t\t\t\t\t<option value=\"5\">상</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"3\" selected>중</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"1\">하</option>\r\n");
      out.write("\t\t\t\t</select> <br /> <label for=\"\">비밀번호</label><input type=\"password\" name=\"pwd\"\r\n");
      out.write("\t\t\t\t\tid=\"pwd1\" placeholder=\"7자 이상\" /><br /> <label for=\"\">비밀번호\r\n");
      out.write("\t\t\t\t\t확인</label><input type=\"password\" name=\"password2\" id=\"pwd2\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"7자 이상\" />\r\n");
      out.write("\t\t\t\t<div class=\"alert-pwd alert\"></div>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"down-btn\" onclick=\"goToStep2()\">\r\n");
      out.write("\t\t\t<i class=\"fas fa-arrow-down\"></i>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<section id=\"step_2\">\r\n");
      out.write("\t\t<div class=\"up-btn\" onclick=\"goToStep1()\">\r\n");
      out.write("\t\t\t<i class=\"fas fa-arrow-up\"></i>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<span class=\"step_1\">2. 우리에게 당신의 관심사를 모두 알려주세요.</span> <span\r\n");
      out.write("\t\t\tclass=\"step_1\">YOGAYO만의 맞춤 코스를 추천해드리겠습니다.</span>\r\n");
      out.write("\t\t<div class=\"interests\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"signUpBtn\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"가입하기\" disabled=\"disabled\" id=\"submitBtn\" onclick=\"alert('회원가입되었습니다.')\" \r\n");
      out.write("\t\t\t\tclass=\"submitBtn\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t</section>\r\n");
      out.write("\t</main>\r\n");
      out.write("\t<script language=JavaScript\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/sign_up_vaild_check.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction goToStep2() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tconsole.log(emailDuplCheck())\r\n");
      out.write("\t\t\tconsole.log(nameVaildCheck())\r\n");
      out.write("\t\t\tconsole.log(birthdayVaildCheck())\r\n");
      out.write("\t\t\tconsole.log(password1VaildCheck())\r\n");
      out.write("\t\t\tconsole.log(password2VaildCheck())\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif (emailDuplCheck() && nameVaildCheck() && birthdayVaildCheck()\r\n");
      out.write("\t\t\t\t\t&& password1VaildCheck() && password2VaildCheck()) {\r\n");
      out.write("\t\t\t\t$('.down-btn i').css({\r\n");
      out.write("\t\t\t\t\tcolor : \"green\",\r\n");
      out.write("\t\t\t\t\t\"border\" : \"1px solid green\"\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\twindow.scrollTo({\r\n");
      out.write("\t\t\t\t\ttop : 1080,\r\n");
      out.write("\t\t\t\t\tbehavior : \"smooth\"\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(\"#profiLevel\").css({\r\n");
      out.write("\t\t\t\t\tcolor : \"green\",\r\n");
      out.write("\t\t\t\t\t\"border-bottom\" : \"2px solid green\",\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('.down-btn i').css({\r\n");
      out.write("\t\t\t\t\tcolor : \"red\",\r\n");
      out.write("\t\t\t\t\t\"border\" : \"1px solid red\"\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(\"#profiLevel\").css({\r\n");
      out.write("\t\t\t\t\tcolor : \"green\",\r\n");
      out.write("\t\t\t\t\t\"border-bottom\" : \"2px solid green\",\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction goToStep1() {\r\n");
      out.write("\t\t\twindow.scrollTo({\r\n");
      out.write("\t\t\t\ttop : 0,\r\n");
      out.write("\t\t\t\tbehavior : \"smooth\"\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
