/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-08-27 06:54:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sign_002dup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/Users/soo/Documents/YOGAYO/YOGAYO/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/YOGAYO/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1598411747000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\" />\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
      out.write("<title>YOGAYO | 회원가입</title>\n");
      out.write("<script src=\"https://kit.fontawesome.com/ae58912594.js\"\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/sign-up.css\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<main>\n");
      out.write("\t\t<section id=\"step_1\">\n");
      out.write("\t\t\t<header>\n");
      out.write("\t\t\t\t<a href=\"/\"><div class=\"logo-wrapper\">\n");
      out.write("\t\t\t\t\t\t<span>YOGAYO</span>\n");
      out.write("\t\t\t\t\t\t<div class=\"box-div\"></div>\n");
      out.write("\t\t\t\t\t</div> </a>\n");
      out.write("\t\t\t</header>\n");
      out.write("\t\t\t<span class=\"welcome\">좋아요! 이제 간단한 두 단계만 거치면 YOGAYO와 함께 하실 수\n");
      out.write("\t\t\t\t있습니다.</span> <span class=\"step_1\">1. 회원가입을 위한 정보를 입력해주세요.</span>\n");
      out.write("\t\t\t<div class=\"sign-up-form\">\n");
      out.write("\t\t\t\t<form action=\"sign-up\" method=\"POST\">\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"keyword\" id=\"keyword\" value=\"false\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<label for=\"\">이메일</label>\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"id\" id=\"email\" placeholder=\"johndoe@example.com\" /> <br /> \n");
      out.write("\t\t\t\t\t\t<div class=\"msgContainer\"><label for=\"\"></label><span class=\"emailVaildMsg\" >이미 사용중이거나 올바르지 않은 이메일입니다.</span><br /></div>\n");
      out.write("\t\t\t\t\t\t<label for=\"\">이름</label>\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"name\" id=\"name\" placeholder=\"3자 이상\" /><br /> \n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<label for=\"\">생년월일</label> <input type=\"date\" name=\"bDate\" id=\"birthDay\" placeholder=\"\" /><br /> <label for=\"\">성별</label>\n");
      out.write("\t\t\t\t\t\t<select name=\"gender\" id=\"gender\">\n");
      out.write("\t\t\t\t\t\t<option value=\"M\">남성</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"F\">여성</option>\n");
      out.write("\t\t\t\t\t</select> <br /> \n");
      out.write("\t\t\t\t\t<label for=\"\">숙련도</label> \n");
      out.write("\t\t\t\t <select name=\"profiLevel\" id=\"profiLevel\">\n");
      out.write("\t\t\t\t\t<option value=\"5\">상</option>\n");
      out.write("\t\t\t\t\t<option value=\"3\" selected>중</option>\n");
      out.write("\t\t\t\t\t<option value=\"1\">하</option>\n");
      out.write("\t\t\t\t</select> <br/>\n");
      out.write("\t\t\t\t\t<label for=\"\">비밀번호</label><input type=\"password\" name=\"pwd\" id=\"pwd1\" placeholder=\"7자 이상\" /><br /> \n");
      out.write("\t\t\t\t\t<label for=\"\">비밀번호 확인</label><input type=\"password\" name=\"password2\" id=\"pwd2\" placeholder=\"7자 이상\" />\n");
      out.write("\t\t\t\t\t<div class=\"alert-pwd alert\"></div>\n");
      out.write("\t\t\t\t\t<br />\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"down-btn\" onclick=\"goToStep2()\">\n");
      out.write("\t\t\t\t<i class=\"fas fa-arrow-down\"></i>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</section>\n");
      out.write("\t\t<section id=\"step_2\">\n");
      out.write("\t\t\t<div class=\"up-btn\" onclick=\"goToStep1()\">\n");
      out.write("\t\t\t\t<i class=\"fas fa-arrow-up\"></i>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<span class=\"step_1\">2. 우리에게 당신의 관심사를 모두 알려주세요.</span> <span\n");
      out.write("\t\t\t\tclass=\"step_1\">YOGAYO만의 맞춤 코스를 추천해드리겠습니다.</span>\n");
      out.write("\t\t\t<div class=\"interests\">\n");
      out.write("\t\t\t\t<span class=\"interest_1 interest\">저강도의</span> <span\n");
      out.write("\t\t\t\t\tclass=\"interest_2 interest\">체력 단련</span> <span\n");
      out.write("\t\t\t\t\tclass=\"interest_3 interest\">영적인 경험</span> <span\n");
      out.write("\t\t\t\t\tclass=\"interest_4 interest\">체중 감량</span> <span\n");
      out.write("\t\t\t\t\tclass=\"interest_5 interest\">균형</span> <span\n");
      out.write("\t\t\t\t\tclass=\"interest_6 interest\">유연성</span> <span\n");
      out.write("\t\t\t\t\tclass=\"interest_7 interest\">임신중에 할 수 있는</span> <span\n");
      out.write("\t\t\t\t\tclass=\"interest_8 interest\">근력 개선</span> <span\n");
      out.write("\t\t\t\t\tclass=\"interest_9 interest\">스트레스 감소</span> <span\n");
      out.write("\t\t\t\t\tclass=\"interest_10 interest\">기분 및 행동 개선</span> <span\n");
      out.write("\t\t\t\t\tclass=\"interest_11 interest\">만성 요통</span> <span\n");
      out.write("\t\t\t\t\tclass=\"interest_12 interest\">우울증</span> <span\n");
      out.write("\t\t\t\t\tclass=\"interest_13 interest\">아이를 위한</span> <span\n");
      out.write("\t\t\t\t\tclass=\"interest_14 interest\">정신건강</span> <span\n");
      out.write("\t\t\t\t\tclass=\"interest_15 interest\">내적 평화</span> <span\n");
      out.write("\t\t\t\t\tclass=\"interest_16 interest\">명상 훈련</span> <span\n");
      out.write("\t\t\t\t\tclass=\"interest_17 interest\">고강도의</span> <span\n");
      out.write("\t\t\t\t\tclass=\"interest_18 interest\">현대 요가</span> <span\n");
      out.write("\t\t\t\t\tclass=\"interest_19 interest\">호흡법</span> <span\n");
      out.write("\t\t\t\t\tclass=\"interest_20 interest\">관절염</span> <span\n");
      out.write("\t\t\t\t\tclass=\"interest_21 interest\">불면증</span> <span\n");
      out.write("\t\t\t\t\tclass=\"interest_22 interest\">친구와 같이 하는</span> <span\n");
      out.write("\t\t\t\t\tclass=\"interest_23 interest\" onclick=\"alert()\">천식</span>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<div id=\"signUpBtn\">\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"가입하기\" disabled=\"disabled\" id=\"submitBtn\"\n");
      out.write("\t\t\t\t\tclass=\"submitBtn\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t</form>\n");
      out.write("\n");
      out.write("\t\t</section>\n");
      out.write("\t</main>\n");
      out.write("\t<script language=JavaScript\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/sign_up_vaild_check.js\"></script>\n");
      out.write("\t<script language=JavaScript\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/sign_up_interests.js\"></script>\n");
      out.write("\t<script>\n");
      out.write("\t\n");
      out.write("\t\tfunction goToStep2() {\n");
      out.write("\t\t\tif (emailDuplCheck() && nameVaildCheck() && birthdayVaildCheck()\n");
      out.write("\t\t\t\t\t&& password1VaildCheck() && password2VaildCheck()) {\n");
      out.write("\t\t\t\t$('.down-btn i').css({\n");
      out.write("\t\t\t\t\tcolor : \"green\",\n");
      out.write("\t\t\t\t\t\"border\" : \"1px solid green\"\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t\twindow.scrollTo({\n");
      out.write("\t\t\t\t\ttop : 1080,\n");
      out.write("\t\t\t\t\tbehavior : \"smooth\"\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t\t$(\"#profiLevel\").css({\n");
      out.write("\t\t\t\t\tcolor : \"green\",\n");
      out.write("\t\t\t\t\t\"border-bottom\" : \"2px solid green\",\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\t$('.down-btn i').css({\n");
      out.write("\t\t\t\t\tcolor : \"red\",\n");
      out.write("\t\t\t\t\t\"border\" : \"1px solid red\"\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t\t$(\"#profiLevel\").css({\n");
      out.write("\t\t\t\t\tcolor : \"green\",\n");
      out.write("\t\t\t\t\t\"border-bottom\" : \"2px solid green\",\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction goToStep1() {\n");
      out.write("\t\t\twindow.scrollTo({\n");
      out.write("\t\t\t\ttop : 0,\n");
      out.write("\t\t\t\tbehavior : \"smooth\"\n");
      out.write("\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\t</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
